import { describe, it, expect } from 'vitest'
import {
  parseScstConf,
  parseScstConfSafe,
} from '../server/utils/scst-conf-parser'

/**
 * Configuration réelle observée sur `nas-dellr730xd`
 * (cf. SDD v1.2 rev.1 §11).
 */
const REAL_CONF = `
# Automatically generated by SCST Configurator v3.7.0.

HANDLER vdisk_fileio {
    DEVICE LINUX {
        filename /mnt/vdisks/fs01/linux
        nv_cache 1
    }
    DEVICE TOOLS {
        filename /mnt/vdisks/fs01/tools
        nv_cache 1
    }
    DEVICE WINDOWS {
        filename /mnt/vdisks/fs01/windows
        nv_cache 1
    }
}

TARGET_DRIVER copy_manager {
    TARGET copy_manager_tgt {
        LUN 0 LINUX
        LUN 1 TOOLS
        LUN 2 WINDOWS
    }
}

TARGET_DRIVER iscsi {
    enabled 0
}

TARGET_DRIVER qla2x00t {
    TARGET 21:00:00:24:ff:91:60:bc {
        HW_TARGET
        enabled 1
        rel_tgt_id 1
        GROUP 60BC {
            LUN 0 TOOLS
            LUN 1 WINDOWS
            LUN 2 LINUX
            INITIATOR 21:00:00:24:ff:55:68:eb
            INITIATOR 21:00:00:24:ff:5e:8d:4c
            INITIATOR 50:01:43:80:09:ae:e0:a0
        }
    }
    TARGET 21:00:00:24:ff:91:60:bd {
        HW_TARGET
        enabled 1
        rel_tgt_id 2
        GROUP 60BD {
            LUN 0 TOOLS
            LUN 1 WINDOWS
            LUN 2 LINUX
            INITIATOR 21:00:00:24:ff:55:68:ea
            INITIATOR 21:00:00:24:ff:5e:8d:4d
            INITIATOR 50:01:43:80:09:ae:e0:a2
        }
    }
}
`

const SIMPLE_ISCSI = `
HANDLER vdisk_blockio {
    DEVICE disk01 {
        filename /dev/sdb
    }
}
TARGET_DRIVER iscsi {
    TARGET iqn.2024-01.com.ibanfirst:storage01 {
        enabled 1
        GROUP servers_prod {
            INITIATOR iqn.1994-05.com.redhat:server01
            LUN 0 disk01 {
                read_only 1
            }
        }
    }
}
`

describe('parseScstConf — SDD v1.2 rev.1 (config réelle ESOS)', () => {
  it('T01 — HANDLER vdisk_fileio + 3 DEVICE', () => {
    const c = parseScstConf(REAL_CONF)
    const h = c.handlers.find((x) => x.name === 'vdisk_fileio')!
    expect(h).toBeDefined()
    expect(h.devices).toHaveLength(3)
    expect(h.devices.map((d) => d.name)).toEqual(['LINUX', 'TOOLS', 'WINDOWS'])
  })

  it('T02 — DEVICE attribut nv_cache 1', () => {
    const c = parseScstConf(REAL_CONF)
    const dev = c.handlers[0].devices.find((d) => d.name === 'LINUX')!
    expect(dev.attrs.nv_cache).toBe('1')
  })

  it('T03 — DEVICE filename', () => {
    const c = parseScstConf(REAL_CONF)
    const dev = c.handlers[0].devices.find((d) => d.name === 'LINUX')!
    expect(dev.filename).toBe('/mnt/vdisks/fs01/linux')
  })

  it('T04 — Driver iscsi avec enabled 0 et 0 target', () => {
    const c = parseScstConf(REAL_CONF)
    const iscsi = c.drivers.find((d) => d.name === 'iscsi')!
    expect(iscsi.enabled).toBe(false)
    expect(iscsi.targets).toHaveLength(0)
  })

  it('T05 — copy_manager : LUNs directs sous TARGET, pas de groupe', () => {
    const c = parseScstConf(REAL_CONF)
    const cm = c.drivers.find((d) => d.name === 'copy_manager')!
    expect(cm.targets).toHaveLength(1)
    const tgt = cm.targets[0]
    expect(tgt.luns).toHaveLength(3)
    expect(tgt.groups).toHaveLength(0)
    expect(tgt.luns.map((l) => l.device)).toEqual(['LINUX', 'TOOLS', 'WINDOWS'])
  })

  it('T06 — Target avec HW_TARGET → hwTarget true', () => {
    const c = parseScstConf(REAL_CONF)
    const t = c.drivers
      .find((d) => d.name === 'qla2x00t')!
      .targets.find((x) => x.name === '21:00:00:24:ff:91:60:bc')!
    expect(t.hwTarget).toBe(true)
  })

  it('T07 — Target avec rel_tgt_id 1 → attrs.rel_tgt_id', () => {
    const c = parseScstConf(REAL_CONF)
    const t = c.drivers
      .find((d) => d.name === 'qla2x00t')!
      .targets.find((x) => x.name === '21:00:00:24:ff:91:60:bc')!
    expect(t.attrs.rel_tgt_id).toBe('1')
  })

  it('T08 — Target avec enabled 1', () => {
    const c = parseScstConf(REAL_CONF)
    const t = c.drivers
      .find((d) => d.name === 'qla2x00t')!
      .targets.find((x) => x.name === '21:00:00:24:ff:91:60:bc')!
    expect(t.enabled).toBe(true)
  })

  it('T09 — GROUP avec 3 INITIATOR WWN', () => {
    const c = parseScstConf(REAL_CONF)
    const t = c.drivers
      .find((d) => d.name === 'qla2x00t')!
      .targets.find((x) => x.name === '21:00:00:24:ff:91:60:bc')!
    const g = t.groups.find((x) => x.name === '60BC')!
    expect(g.initiators).toEqual([
      '21:00:00:24:ff:55:68:eb',
      '21:00:00:24:ff:5e:8d:4c',
      '50:01:43:80:09:ae:e0:a0',
    ])
  })

  it('T10 — GROUP avec 3 LUN', () => {
    const c = parseScstConf(REAL_CONF)
    const t = c.drivers
      .find((d) => d.name === 'qla2x00t')!
      .targets.find((x) => x.name === '21:00:00:24:ff:91:60:bc')!
    const g = t.groups.find((x) => x.name === '60BC')!
    expect(g.luns).toHaveLength(3)
    expect(g.luns.map((l) => `${l.id}:${l.device}`)).toEqual([
      '0:TOOLS',
      '1:WINDOWS',
      '2:LINUX',
    ])
  })

  it('T11 — 2 targets dans le driver qla2x00t', () => {
    const c = parseScstConf(REAL_CONF)
    const qla = c.drivers.find((d) => d.name === 'qla2x00t')!
    expect(qla.targets).toHaveLength(2)
    expect(qla.enabled).toBe(true) // pas de "enabled 0" → true par défaut
  })

  it('T15 — fichier vide → config vide sans erreur', () => {
    const c = parseScstConf('')
    expect(c).toEqual({ handlers: [], drivers: [], deviceGroups: [] })
  })

  it('parseScstConfSafe accepte whitespace seul', () => {
    expect(parseScstConfSafe('   \n  \n').handlers).toHaveLength(0)
    expect(parseScstConfSafe('   \n  \n').drivers).toHaveLength(0)
  })

  it('compatibilité iSCSI — IQN + LUN avec read_only 1', () => {
    const c = parseScstConf(SIMPLE_ISCSI)
    const t = c.drivers[0].targets[0]
    expect(t.name).toBe('iqn.2024-01.com.ibanfirst:storage01')
    expect(t.hwTarget).toBe(false)
    expect(t.luns).toHaveLength(0)
    const lun = t.groups[0].luns[0]
    expect(lun.readOnly).toBe(true)
  })

  it('Driver sans "enabled" garde enabled=true par défaut', () => {
    const c = parseScstConf(REAL_CONF)
    const cm = c.drivers.find((d) => d.name === 'copy_manager')!
    expect(cm.enabled).toBe(true)
  })

  it('Target sans HW_TARGET garde hwTarget=false par défaut', () => {
    const c = parseScstConf(REAL_CONF)
    const cm = c.drivers.find((d) => d.name === 'copy_manager')!
    expect(cm.targets[0].hwTarget).toBe(false)
  })

  it('groups are unique per target with distinct initiator and LUN sets', () => {
    const conf = `
TARGET_DRIVER iscsi {
    TARGET iqn.2000-01.com.example:t1 {
        GROUP hosts_a {
            INITIATOR iqn.a
            LUN 0 dev_a
        }
        GROUP hosts_b {
            INITIATOR iqn.b
            LUN 1 dev_b
        }
    }
}
HANDLER vdisk_fileio {
    DEVICE dev_a { filename /a }
    DEVICE dev_b { filename /b }
}
`
    const c = parseScstConf(conf)
    const t = c.drivers[0].targets[0]
    expect(t.groups).toHaveLength(2)
    expect(t.groups.map(g => g.name).sort()).toEqual(['hosts_a', 'hosts_b'])
    expect(t.groups[0].initiators).toEqual(['iqn.a'])
    expect(t.groups[1].luns[0].device).toBe('dev_b')
  })

  it('parse pattern initiator and IB-style initiator', () => {
    const conf = `
TARGET_DRIVER iscsi {
    TARGET iqn.2000-01.com.example:t2 {
        GROUP wild {
            INITIATOR iqn.1994-05.com.redhat:*
            INITIATOR 0x0002c902004098ecee8e13
        }
    }
}
`
    const c = parseScstConf(conf)
    const g = c.drivers[0].targets[0].groups[0]
    expect(g.initiators).toContain('iqn.1994-05.com.redhat:*')
    expect(g.initiators).toContain('0x0002c902004098ecee8e13')
  })
})
